### ISSUE TITLE
[EPIC] BOOTSTRAPPING

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#1]
There should be two ways to initialize a project.
- [x] #31
- [x] Download latest release

Once initialized;
- [x] Run `npm i // or yarn` to install dependencies.
- [x] [CLI] `server init <name> -i` CLI command to install dependencies right after initialized the project
- [x] Run `npm start // or yarn start` to start the application and it will be available on `http://localhost:5000` (default)

On the first run;
- [x] Show start screen to gather some information to setup the server instance. (This is much similar to WordPress Installation screen.)
- [x] Ask for `appName` `userName` `screenName` `password` `email` `database (default: JsonDB)`
- [x] Once user click on `Proceed`, update all the necessary records in the database, and user should be force login to the admin area.
- [x] Should update `.env` file accordingly.

**Comment by thinkholic** [comment]
Bootstrapping v1 is done.
