### ISSUE TITLE
[EPIC] DATABASE

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#23]
- [x] JsonDB - default database
- [x] https://github.com/thinkholic/backdrop-js/issues/11
- [ ] https://github.com/thinkholic/backdrop-js/issues/12
- [ ] SQLLite

**Comment by kasunben** [comment]
### Backdrop Eloquent (ORM/ODM)

- [x] Wrapper for MongoDB
- [x] Wrapper for JsonDB

```
db()
db('users').
db('users').find();
```
