### ISSUE TITLE
[EPIC] RESTful - API

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#24]
- [x] RESTful
- [ ] https://github.com/thinkholic/backdrop-js/issues/14
- [ ] Deploy as Serverless functions
- [ ] Add support for `static` Resource Type
- [ ] Add support for `custom` Resource Type (users should able to add custom logic using web code editor. ([monac-editor](https://www.npmjs.com/package/@monaco-editor/react))
- [x] Should able support to select `resource-type` from resource creation screen

**Comment by kasunben** [comment]
### API Spec
- [ ] Should update [here](https://github.com/thinkholic/json-api-spec).

#### MIME Types
- [x] `application/json.`

#### Patterns
- [x] `GET /:resource`
- [ ] `GET /:resource?query={}&fields=[]&limit=10&offset=0`
- [ ] `GET /:resource?fields=[]&limit=10&offset=0`
- [x] `GET /:resource?limit=10&offset=0`
- [x] `GET /:resource/:id`
- [ ] `GET /:resource/:id/:sub`
- [x] `POST /:resource`
- [x] `PUT /:resource`
- [x] `PATCH /:resource`
- [x] `DELETE /:resource`

#### Response Object
- [x] Response Object
```
{
  code: Number
  data: Array|Object,
  errors: Array
}
```
