### ISSUE TITLE
[EPIC] BUILLD SCRIPTS

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#25]
- [ ] Ideally we need a separate set of build scripts to manage, serve the application. (Similar to `react-scripts` in `CRA`)

#### Tasks
- [x] Write a bash script to manage the build
- [x] https://github.com/thinkholic/backdrop-js/issues/20

**Comment by kasunben** [comment]
- [ ] Modify package json in the build process
  - [ ] application name
  - [ ] version
  - [ ] Replace `yarn` to `npm` in `scripts`
  - [ ] Git references

**Comment by kasunben** [comment]
Build script can write with https://jakejs.com/
