### ISSUE TITLE
[EPIC] CLI

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#26]
#### Tasks
- [x] https://github.com/thinkholic/backdrop-js/issues/15
- [ ] #30
- [ ] #32
- [ ] Implement `server down` (Stop development server)
- [ ] Implement `server deploy` (Start deployment agent)
