### ISSUE TITLE
[EPIC] USER

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#3]
### Tasks
- [x] https://github.com/thinkholic/backdrop-js/issues/2
- [x] https://github.com/thinkholic/backdrop-js/issues/22
- [ ] https://github.com/thinkholic/backdrop-js/issues/44
- [ ] #45
- [x] Should have `/core/users` resource
- [x] In the admin portal, there should be a section as `Users`.
Similar to WordPress User Section.
- [x] Should list all the users in a table with `username` , `name`, `email`, `userRole` etc.
- [x] Should be able to edit/modify and delete users
- [x] Add new users
- [ ] Should support for multiple user roles and custom capabilities graph
- [ ] Should be able to have user avatar.
- [ ] Admin users should be able include new custom fields
- [ ] Limit add/edit/delete user options only for admins
- [ ] Signup option should be able to enable and disable from admin portal (Settings)
