### ISSUE TITLE
[EPIC] CRUD

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#34]
### Revamp CRUD Section
- [x] This is should be a separate section
- [ ] Hide CRUD section when no resources
- [ ] Show dynamic and rich data table fro each resource
- [ ] Lookup Fields for linked resources 
- [ ] Input field for array type
