### ISSUE TITLE
[EPIC] CONFIG

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#4]
- [x] Consume `/core/config` resource
- [x] Should be available `settings` section in the portal
- [x] Input fields are `appName`, `appDesc`, `baseUrl`, `databaseConfigs`, `timeZoneSettings`, `adminEmail` etc.
- [ ] Update `.env` file accordingly
