### ISSUE TITLE
[EPIC] RESTful - CORE

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#46]
- [x] `GET /core/config`
- [x] `GET /core/config/:type`
- [x] `POST /core/config/:type`
- [x] `PATCH /core/config/:type`
- [x] `GET /core/media`
- [x] `POST /core/media`
- [x] `GET /core/resource`
- [ ] `GET /core/resource/:name`
- [x] `POST /core/resource`
- [ ] `PATCH /core/resource/:name`
- [ ] `PUT /core/resource/:name`
- [ ] `DELETE /core/resource/:name`
- [x] `GET /core/user`
- [x] `GET /core/user/:id`
- [x] `POST /core/user`
- [x] `PATCH /core/user/:id`
- [x] `PUT /core/user/:id`
- [x] `DELETE /core/user/:id`
- [x] `POST /core/email`
