### ISSUE TITLE
[EPIC] E-MAIL

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#5]
- [x] `/core/email` resource 2e14803f20133d6828c8b0d91313503ea899eff6
- [x] #60
- [ ] SMTP Settings screen in settings/ in admin portal
- [ ] Update `.env` accordingly
