### ISSUE TITLE
[EPIC] LOGGING

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#57]
Log everything: transactions, data mutations, requests etc.

- [ ] Should have a collection named `logs` or a new document in `config` collection with `{type: "logs"}`
  - [ ] Log Types: `error` `warning` `log` `debug` `info`
- [ ] Should have a new section for Log Explorer
  - [ ] List, Filter, Search logs
- [ ] Log:
  - [ ] CRUD (resource)
