### ISSUE TITLE
[EPIC] MEDIA LIBRARY

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#6]
Similar to WordPress Media Library.

- [x] `/core/media` resource
- [x] Users should be able to upload media files using the `Media Library` section in admin portal
- [ ] Should be able to edit/modify, delete previously uploaded media and it's metadata.

**Comment by kasunben** [comment]
- [ ] Change `media` directory name to `assets`
