### ISSUE TITLE
[EPIC] CODE EDITOR

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#63]
### Frontend
- [ ] Should have a separate module for Code Editor
- [ ] Should list all the files under custom handlers in categorised manner (Left Sidebar)
- [ ] Load the particular file to the Editor in the right pane.

### API
- [ ] `GET /core/:resource/handler/<get|post|put|patch|delete>`
- [ ] `POST /core/:resource/handler/<get|post|put|patch|delete>`
- [ ] `PUT /core/:resource/handler/<get|post|put|patch|delete>`
- [ ] `PATCH /core/:resource/handler/<get|post|put|patch|delete>`
- [ ] `DELETE /core/:resource/handler/<get|post|put|patch|delete>`
