### ISSUE TITLE
[EPIC] SCHEMA BUILDER

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#64]
- [x] Name
- [x] Label
- [x] Type
- [x] Length
- [x] Required
- [x] Unique
- [x] Auto

**Comment by kasunben** [comment]
- [x] Let users to delete fields once added
- [x] Hide length field for Boolean, Array, Obect
- [x] Show default option for Boolean
- [x] Allow for auto-generated id (_id)
- [ ] Support for nested schemas
- [x] #73 
- [ ] Lookup Control
- [x] `createdAt` and `updatedAt`
- [ ] Placeholder
