### ISSUE TITLE
[EPIC] MESSAGE INBOX

### ISSUE THREAD

**Issue by kasunben** [thinkholic/backdrop-js#69]
- [ ] All the users registered in the system should be able to send messages each other on platform.
- [ ] There should be a message list and message view in the module
- [ ] Should be able to send emails to user groups 
- [ ] Send email notifications to users' email address
- [ ] Users should be able reply to emails by replying to emails from their email accounts (PHASE-2)
- [ ] Should be able to create email groups (PHASE-2)
