### ISSUE TITLE
[EPIC] RESOURCES

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#7]
#### RESTful
- [x] Consume `/core/resources` and `/<namespace [api]>/:resource/:id?` resources
- [x] List all the resources already created in table view (`/resources`)
- [x] `Delete` option should be available on Action Column in the Table
- [x] Once user click on resource in the table it should redirect to `/resources/:id`
  - [x] Allow Edit resource config
- [x]  Create a new resource (`/resource/create`)
  - [x] Input fields: `name` `type` `protected` .. etc
  - [x] Generate `schema` according to user inputs (Refer [these samples](https://github.com/thinkholic/backdrop-js/tree/master/.samples))
