### ISSUE TITLE
[EPIC] AUTH

### ISSUE THREAD

**Issue by thinkholic** [thinkholic/backdrop-js#8]
- [x] #10
- [ ] #54
- [ ] Hide resource fetching if they are flagged as `private`
- [ ] Setting up OAuth2 Server and workflow
  - [ ] This feature can be placed under `settings > oauth2`
  - [ ] Users (admin) should be able to create clients/apps and generate credentials (`clientId`, `clientSecret`) for each client.
  - [ ] Those credentials will be use authenticate resource endpoints as specified. 
  - [ ] Any numbers of clients can be added
- [ ] Implement auth for dynamic resources
  - [ ] `default` - all the RESTful HTTP Methods
    - [x] no auth
    - [ ] basic auth
    - [ ] advanced auth
  - [ ] `proxy`
    - [x] no auth
    - [ ] basic auth
    - [ ] advance auth
